### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by ZuowenWang0000** [davidstutz/disentangling-robustness-generalization#2]
Hello David,
Thanks for your work!
When I testing verify_hypothesis, in learned_variational_auto_encoder line 425:`output = getattr(self, name)(output)`
 it always return me the following error:
`RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

So what i did is change the View method in common.torch from .view to .reshape.

Is this just a torch version issue? Is it safe to do so?

Thanks for your help in advance!

**Comment by davidstutz** [comment]
Should be safe to do so. For this project I used one of the earliest PyTorch versions and I encountered similar issues over the years when upgrading to newer versions. Alternatively, you could also call `.contiguous()` in the view module.
